"""refactor sizes to m2m

Revision ID: 8dc32747088f
Revises: 692773e0d32c
Create Date: 2026-05-11 02:22:41.930192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dc32747088f'
down_revision: Union[str, Sequence[str], None] = '692773e0d32c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_size_id'), 'size', ['id'], unique=False)
    op.create_table('product_size_association',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('size_id', sa.BigInteger(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'size_id')
    )
    op.drop_index(op.f('ix_product_size_id'), table_name='product_size')
    op.drop_table('product_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_size',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('size', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('stock', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('product_size_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_size_pkey'))
    )
    op.create_index(op.f('ix_product_size_id'), 'product_size', ['id'], unique=False)
    op.drop_table('product_size_association')
    op.drop_index(op.f('ix_size_id'), table_name='size')
    op.drop_table('size')
    # ### end Alembic commands ###
