"""link_brand_to_product

Revision ID: e214d0b0456f
Revises: af288ba57260
Create Date: 2026-05-15 19:30:13.106409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e214d0b0456f'
down_revision: Union[str, Sequence[str], None] = 'af288ba57260'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'product', 'brand', ['brand_id'], ['id'])
    op.drop_column('product', 'brand')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('brand', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'brand_id')
    # ### end Alembic commands ###
